#!/usr/bin/env bash
dry_run=""

if [[ -z "$XDG_CONFIG_HOME" ]]; then
    echo "no xdg config"
    echo "using $HOME/.config instead"
    XDG_CONFIG_HOME=$HOME/.config
fi

if [[ -z "$DEV_ENV" ]]; then
    echo "no dev env present"
    exit 1
fi

if [[ $1 == "--dry" ]]; then
    dry_run="1"
fi

log() {
    if [[ $dry_run == "1" ]]; then
        echo -e "[DRY_RUN]: $1"
    else
        echo -e "$1"
    fi
}

log "env: $DEV_ENV"

# Update directory
update_directory() {
    log "copying files from: $1"
    pushd $1 &> /dev/null
    (
        configs=`find . -mindepth 1 -maxdepth 1 -type d`
        for c in $configs; do
            directory=${2%/}/${c#./}
            log  "\tremoving: rm -rf $directory"

            if [[ -z $dry_run ]]; then
                rm -rf $directory
            fi

            log "\tcopying env: cp $c $2"
            if [[ -z $dry_run ]]; then
                cp -r ./$c $2
            fi
        done
    )
    popd &> /dev/null
}

# Update single file
update_file() {
    log "removing: $2"
    if [[ -z $dry_run ]]; then
        rm $2
    fi
    log "copying: $1 to $2"
    if [[ -z $dry_run ]]; then
       cp $1 $2 
    fi

}

update_directory $DEV_ENV/env/.config $XDG_CONFIG_HOME
# idk if i wanna remove everything from .local 
update_directory $DEV_ENV/env/.local $HOME/.local

update_file $DEV_ENV/tmux-sessionizer/tmux-sessionizer $HOME/.local/scripts/tmux-sessionizer
update_file $DEV_ENV/tmux-sessionizer/.workspace_dirs $HOME/.workspace_dirs
update_file $DEV_ENV/env/.zshrc $HOME/.zshrc
update_file $DEV_ENV/env/.zsh_profile $HOME/.zsh_profile
update_file $DEV_ENV/env/.tmux-sessioniser $HOME/.tmux-sessioniser
update_file $DEV_ENV/dev-env $HOME/.local/scripts/dev-env
